apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-24-12
spec:
  selector:
    matchLabels:
      app: triton-24-12
  template:
    metadata:
      labels:
        app: triton-24-12
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: nvcr.io/nvidia/tritonserver:24.12-py3-sdk
        imagePullPolicy: IfNotPresent
        name: triton
        resources:
          limits:
            nvidia.com/gpu: "1"
